name: Build Release manually

on:
  workflow_dispatch:

jobs:
  linux-windows-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Init submodules
        run: git submodule update --init --checkout --recursive
      - name: Build release image
        run: docker compose -f compose.release.yml build release
      - name: Build Linux and Windows artifacts
        run: docker compose -f compose.release.yml run --rm release
      - name: Save deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-build
          path: |
            dist/*.deb

      - name: Save exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe-build
          path: |
            dist/*.exe

      - name: Save snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap-build
          path: |
            dist/*.snap

      - name: Save windows zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip-build
          path: |
            outputs/cyberiada-*-windows.zip

      - name: Save AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage-build
          path: |
            dist/*.AppImage

  mac-build:
    runs-on: 'macos-latest'

    needs: linux-windows-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build
      - run: npm run bundle:mac

      - name: Save dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: dmg-build
          path: |
            dist/*.dmg
